version: "3.0"

services:
  reverse-proxy:
    image: traefik:v2.1.3
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.le.acme.email=martin.eigenmann@unisg.ch
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --providers.docker.exposedByDefault=false
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  
  tapas-tasks:
    image: openjdk
    command: "java -jar /data/tapas-tasks-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-tasks.rule=Host(`tapas-tasks.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-tasks.service=tapas-tasks"
      - "traefik.http.services.tapas-tasks.loadbalancer.server.port=8081"
      - "traefik.http.routers.tapas-tasks.tls=true"
      - "traefik.http.routers.tapas-tasks.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-tasks.tls.certresolver=le"

  tapas-roster:
    image: openjdk
    command: "java -jar /data/tapas-roster-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-roster.rule=Host(`tapas-roster.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-roster.service=tapas-roster"
      - "traefik.http.services.tapas-roster.loadbalancer.server.port=8082"
      - "traefik.http.routers.tapas-roster.tls=true"
      - "traefik.http.routers.tapas-roster.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-roster.tls.certresolver=le"

  tapas-executor-pool:
    image: openjdk
    command: "java -jar /data/tapas-executor-pool-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-executor-pool.rule=Host(`tapas-executor-pool.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-executor-pool.service=tapas-executor-pool"
      - "traefik.http.services.tapas-executor-pool.loadbalancer.server.port=8083"
      - "traefik.http.routers.tapas-executor-pool.tls=true"
      - "traefik.http.routers.tapas-executor-pool.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-executor-pool.tls.certresolver=le"

  tapas-auction-house:
    image: openjdk
    command: "java -jar /data/tapas-auction-house-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-auction-house.rule=Host(`tapas-auction-house.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-auction-house.service=tapas-auction-house"
      - "traefik.http.services.tapas-auction-house.loadbalancer.server.port=8085"
      - "traefik.http.routers.tapas-auction-house.tls=true"
      - "traefik.http.routers.tapas-auction-house.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-auction-house.tls.certresolver=le"

  tapas-executor-1:
    image: openjdk
    command: "java -jar /data/tapas-executor-1-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-executor-1.rule=Host(`tapas-executor-1.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-executor-1.service=tapas-executor-1"
      - "traefik.http.services.tapas-executor-1.loadbalancer.server.port=8091"
      - "traefik.http.routers.tapas-executor-1.tls=true"
      - "traefik.http.routers.tapas-executor-1.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-executor-1.tls.certresolver=le"

  tapas-executor-2:
    image: openjdk
    command: "java -jar /data/tapas-executor-2-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-executor-2.rule=Host(`tapas-executor-2.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-executor-2.service=tapas-executor-2"
      - "traefik.http.services.tapas-executor-2.loadbalancer.server.port=8092"
      - "traefik.http.routers.tapas-executor-2.tls=true"
      - "traefik.http.routers.tapas-executor-2.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-executor-2.tls.certresolver=le"
