version: "3.0"

services:
  reverse-proxy:
    image: traefik:v2.1.3
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.le.acme.email=martin.eigenmann@unisg.ch
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --providers.docker.exposedByDefault=false
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  
  tapas-tasks:
    image: openjdk
    command: "java -jar /data/tapas-tasks-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-tasks.rule=Host(`tapas-tasks.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-tasks.service=tapas-tasks"
      - "traefik.http.services.tapas-tasks.loadbalancer.server.port=8081"
      - "traefik.http.routers.tapas-tasks.tls=true"
      - "traefik.http.routers.tapas-tasks.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-tasks.tls.certresolver=le"

  tapas-roster:
    image: openjdk
    command: "java -jar /data/tapas-roster-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-roster.rule=Host(`tapas-roster.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-roster.service=tapas-roster"
      - "traefik.http.services.tapas-roster.loadbalancer.server.port=8082"
      - "traefik.http.routers.tapas-roster.tls=true"
      - "traefik.http.routers.tapas-roster.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-roster.tls.certresolver=le"

  tapas-executor-robot:
    image: openjdk
    command: "java -jar /data/tapas-executor-robot-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-executor-robot.rule=Host(`tapas-executor-robot.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-executor-robot.service=tapas-executor-robot"
      - "traefik.http.services.tapas-executor-robot.loadbalancer.server.port=8084"
      - "traefik.http.routers.tapas-executor-robot.tls=true"
      - "traefik.http.routers.tapas-executor-robot.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-executor-robot.tls.certresolver=le"

  tapas-executor-digital:
    image: openjdk
    command: "java -jar /data/tapas-executor-digital-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tapas-executor-digital.rule=Host(`tapas-executor-digital.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.tapas-executor-digital.service=tapas-executor-digital"
      - "traefik.http.services.tapas-executor-digital.loadbalancer.server.port=8085"
      - "traefik.http.routers.tapas-executor-digital.tls=true"
      - "traefik.http.routers.tapas-executor-digital.entryPoints=web,websecure"
      - "traefik.http.routers.tapas-executor-digital.tls.certresolver=le"

  app:
    image: openjdk
    command: "java -jar /data/app-0.1.0.jar"
    restart: unless-stopped
    volumes:
      - ./:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.${PUB_IP}.nip.io`)"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.entryPoints=web,websecure"
      - "traefik.http.routers.app.tls.certresolver=le"
