# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - run: mkdir ./target

    - name: Build App Service with Maven
      run: mvn -f app/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./app/target/app-0.1.0.jar ./target

    - name: Build TAPAS Task Service with Maven
      run: mvn -f tapas-tasks/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-tasks/target/tapas-tasks-0.0.1-SNAPSHOT.jar ./target

    - name: Build TAPAS Roster Service with Maven
      run: mvn -f tapas-roster/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-roster/target/tapas-roster-0.0.1-SNAPSHOT.jar ./target

    - name: Build TAPAS Executor Pool Service with Maven
      run: mvn -f tapas-executor-pool/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-pool/target/tapas-executor-pool-0.0.1-SNAPSHOT.jar ./target

    - name: Build TAPAS Executor Computation Service with Maven
      run: mvn -f tapas-executor-computation/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-computation/target/tapas-executor-computation-0.0.1-SNAPSHOT.jar ./target

    - name: Build TAPAS Executor Big Robot Service with Maven
      run: mvn -f tapas-executor-bigrobot/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-bigrobot/target/tapas-executor-bigrobot-0.0.1-SNAPSHOT.jar ./target

    - name: Build TAPAS Auction House Service with Maven
      run: mvn -f tapas-auction-house/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-auction-house/target/tapas-auction-house-0.0.1-SNAPSHOT.jar ./target

    - run: cp docker-compose.yml ./target
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: app
        path: ./target/
    
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, ]
    steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: Copy host via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      with:
        source: "app/*"
        target: "/home/${{ secrets.SSH_USER }}/"
        strip_components: 1
        rm: false
        overwrite: true

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/
          touch acme.json
          sudo chmod 0600 acme.json
          sudo echo "PUB_IP=$(wget -qO- http://ipecho.net/plain | xargs echo)" | sed -e 's/\./-/g' > .env
          sudo docker-compose up -d --build --remove-orphans --force-recreate
