# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    
    - run: mkdir ./target

    - name: Build Tasks Service
      run: mvn -f tapas-tasks/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-tasks/target/tapas-tasks-0.0.1-SNAPSHOT.jar ./target
    
    - name: Build Roster Service
      run: mvn -f tapas-roster/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-roster/target/tapas-roster-0.0.1-SNAPSHOT.jar ./target
    
    - name: Build Executor Pool Service
      run: mvn -f tapas-executor-pool/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-pool/target/tapas-executor-pool-0.0.1-SNAPSHOT.jar ./target
    
    - name: Build Executor 1
      run: mvn -f tapas-executor-1/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-1/target/tapas-executor-1-0.0.1-SNAPSHOT.jar ./target
    
    - name: Build Executor 2
      run: mvn -f tapas-executor-2/pom.xml --batch-mode --update-snapshots verify
    - run: cp ./tapas-executor-2/target/tapas-executor-2-0.0.1-SNAPSHOT.jar ./target



    - run: cp docker-compose.yml ./target
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: app
        path: ./target/
    
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, ]
    if: github.ref == 'refs/heads/master' && github.event.action == 'created'
    steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: Copy host via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      with:
        source: "app/*"
        target: "/home/${{ secrets.SSH_USER }}/"
        strip_components: 1
        rm: false
        overwrite: true

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/
          touch acme.json
          sudo chmod 0600 acme.json
          sudo echo "PUB_IP=$(wget -qO- http://ipecho.net/plain | xargs echo)" | sed -e 's/\./-/g' > .env
          sudo docker-compose up -d
    
    
        
